language: generic
sudo: required # To run docker in tests, sudo is required
services: # Docker cli instance needs to be running to build and run tests on image
  - docker

before_install: # Steps to do before running test
  - docker build -t shashs28/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shashs28/docker-react npm run test -- --coverage

deploy: # Deploying application to aws beanstalk
  provider: elasticbeanstalk # Some providers like abs, digital ocean etc. come with travis ci
  region: "us-west-2" # Region of aws beanstalk instance
  app: "docker-react" # Name of app name in beanstalk
  env: "Docker-env" # Actual app running on app in environment, created while creating beanstalk
  bucket_name: "BKT_NAME"
  bucket_path: "docker-react" # Folder inside bucket to put deployment code in
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY # Pulls key vale using env variables set in travis ci portal
  secret_access_key: "$AWS_SECRET_KEY"
  