version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev # Test does not need port mappings because it does not use them
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # Overiding the default dockerfile command "npm start"

