FROM node:16-alpine

WORKDIR /app

COPY ./package.json .
RUN npm install

RUN mkdir /app/node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

# RUN chown -R node /app/node_modules
# USER node

CMD ["npm", "run", "start"]